### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by anthonyjclarke** [dragondaud/myClock#3]
Wondering if you could assist, probably a newbie issue... but followed all instructions re libraries etc but get these errors ;-)

Arduino: 1.8.7 (Mac OS X), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, 16M (15M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Build options changed, rebuilding all
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/NTP.ino: In function 'String getIPlocation()':
NTP:9:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, const char [23])'
   if (!http.begin(wifi, URL)) {
                            ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/NTP.ino:9:28: note: candidates are:
In file included from /Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/myClock_V.917.ino:7:0:
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)
     bool begin(String url);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)
     bool begin(String host, uint16_t port, String uri = "/");
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)
     bool begin(String url, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)
     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)
     bool begin(String url, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)
     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)
     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/NTP.ino: In function 'int getOffset(String)':
NTP:61:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, String&)'
   if (!http.begin(wifi, URL)) {
                            ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/NTP.ino:61:28: note: candidates are:
In file included from /Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/myClock_V.917.ino:7:0:
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)
     bool begin(String url);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)
     bool begin(String host, uint16_t port, String uri = "/");
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)
     bool begin(String url, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)
     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)
     bool begin(String url, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)
     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)
     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/Weather.ino: In function 'void getWeather()':
Weather:16:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, String&)'
   if (!http.begin(wifi, URL)) {
                            ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/Weather.ino:16:28: note: candidates are:
In file included from /Volumes/Macintosh HD 2/Users/Documents/Arduino/myClock_V.917/myClock_V.917.ino:7:0:
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)
     bool begin(String url);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)
     bool begin(String host, uint16_t port, String uri = "/");
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)
     bool begin(String url, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)
     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)
     bool begin(String url, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)
     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)
     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));
          ^
/Volumes/Macintosh HD 2/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided
exit status 1
no matching function for call to 'HTTPClient::begin(WiFiClient&, const char [23])'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by anthonyjclarke** [comment]
Tried a clean Arduino install on a Windows machine, same issue

Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, 16M (15M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

C:\Users\Ant\Documents\Arduino\myClock_V.917\NTP.ino: In function 'String getIPlocation()':

NTP:9:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, const char [23])'

   if (!http.begin(wifi, URL)) {

                            ^

C:\Users\Ant\Documents\Arduino\myClock_V.917\NTP.ino:9:28: note: candidates are:

In file included from C:\Users\Ant\Documents\Arduino\myClock_V.917\myClock_V.917.ino:7:0:

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)

     bool begin(String url);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)

     bool begin(String host, uint16_t port, String uri = "/");

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)

     bool begin(String url, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)

     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)

     bool begin(String url, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)

     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)

     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided

C:\Users\Ant\Documents\Arduino\myClock_V.917\NTP.ino: In function 'int getOffset(String)':

NTP:61:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, String&)'

   if (!http.begin(wifi, URL)) {

                            ^

C:\Users\Ant\Documents\Arduino\myClock_V.917\NTP.ino:61:28: note: candidates are:

In file included from C:\Users\Ant\Documents\Arduino\myClock_V.917\myClock_V.917.ino:7:0:

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)

     bool begin(String url);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)

     bool begin(String host, uint16_t port, String uri = "/");

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)

     bool begin(String url, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)

     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)

     bool begin(String url, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)

     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)

     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided

C:\Users\Ant\Documents\Arduino\myClock_V.917\Weather.ino: In function 'void getWeather()':

Weather:16:28: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, String&)'

   if (!http.begin(wifi, URL)) {

                            ^

C:\Users\Ant\Documents\Arduino\myClock_V.917\Weather.ino:16:28: note: candidates are:

In file included from C:\Users\Ant\Documents\Arduino\myClock_V.917\myClock_V.917.ino:7:0:

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note: bool HTTPClient::begin(String)

     bool begin(String url);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:137:10: note:   candidate expects 1 argument, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note: bool HTTPClient::begin(String, uint16_t, String)

     bool begin(String host, uint16_t port, String uri = "/");

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:138:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note: bool HTTPClient::begin(String, String)

     bool begin(String url, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:140:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note: bool HTTPClient::begin(String, uint16_t, String, String)

     bool begin(String host, uint16_t port, String uri, String httpsFingerprint);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:141:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note: bool HTTPClient::begin(String, const uint8_t*)

     bool begin(String url, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:143:10: note:   no known conversion for argument 1 from 'WiFiClient' to 'String'

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note: bool HTTPClient::begin(String, uint16_t, String, const uint8_t*)

     bool begin(String host, uint16_t port, String uri, const uint8_t httpsFingerprint[20]);

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:144:10: note:   candidate expects 4 arguments, 2 provided

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note: bool HTTPClient::begin(String, uint16_t, String, bool, String)

     bool begin(String host, uint16_t port, String uri, bool https, String httpsFingerprint)  __attribute__ ((deprecated));

          ^

C:\Users\Ant\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:146:10: note:   candidate expects 5 arguments, 2 provided

Weather:84:69: error: no matching function for call to 'PxMATRIX::getTextBounds(String&, int, const byte&, int16_t*, int16_t*, uint16_t*, uint16_t*)'

         display.getTextBounds(description, 0, row4, &x1, &y1, &w, &h);

                                                                     ^

C:\Users\Ant\Documents\Arduino\myClock_V.917\Weather.ino:84:69: note: candidates are:

In file included from C:\Users\Ant\Documents\Arduino\libraries\PxMatrix-master/PxMatrix.h:27:0,

                 from sketch\display.h:9,

                 from C:\Users\Ant\Documents\Arduino\myClock_V.917\myClock_V.917.ino:14:

C:\Users\Ant\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:69:5: note: void Adafruit_GFX::getTextBounds(char*, int16_t, int16_t, int16_t*, int16_t*, uint16_t*, uint16_t*)

     getTextBounds(char *string, int16_t x, int16_t y,

     ^

C:\Users\Ant\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:69:5: note:   no known conversion for argument 1 from 'String' to 'char*'

C:\Users\Ant\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:71:5: note: void Adafruit_GFX::getTextBounds(const __FlashStringHelper*, int16_t, int16_t, int16_t*, int16_t*, uint16_t*, uint16_t*)

     getTextBounds(const __FlashStringHelper *s, int16_t x, int16_t y,

     ^

C:\Users\Ant\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:71:5: note:   no known conversion for argument 1 from 'String' to 'const __FlashStringHelper*'

exit status 1
no matching function for call to 'HTTPClient::begin(WiFiClient&, const char [23])'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by dragondaud** [comment]
This project requires the git version of ESP8266 Arduino core, and it looks like you are using a release version, which is much older. It also requires latest version of various libraries, too. The installArduino.sh script isn't written for MacOS, but it has the necessary steps to get things installed, after the linux stuff at the beginning. [Using git version](https://github.com/esp8266/Arduino#using-git-version-basic-instructions)
