### ISSUE TITLE
After months of running / now not working #401 - time wong

### ISSUE THREAD

**Issue by anthonyjclarke** [dragondaud/myClock#9]
After a period of functioning for months, stopped working with and error 401, and the time display not accurate. Did a reset, uploaded code again. Here is the Serial Log.... and photo taken after restart, seems to get location and correct time but display something different...

sd�lܟ<�⸮l⸮|��⸮�l⸮#|⸮⸮�⸮�⸮s⸮#⸮�c⸮⸮'o⸮dg'⸮⸮⸮�c�p⸮⸮dsdrd8⸮g⸮���⸮�lĜ��cn⸮|�$⸮�⸮c⸮⸮o'⸮�l⸮⸮d�⸮��gnd���gs⸮ۓn�#⸮�d�;⸮⸮g�c�⸮�l⸮c$⸮p⸮⸮⸮ćd`�⸮⸮g⸮�
19:28:52.641 -> readSPIFFS: mounted
WiFi: myClock-022152 192.168.1.166
getIPlocation: Telstra Corporation, New South Wales, AU, Australia/Sydney
19:29:14.963 -> setup: 2112, Australia/Sydney, true
setNTP: configure NTP ...... OK
19:29:18.619 -> setNTP: next timezone check @ Fri Mar 15 02:00:00 2019
08:29
getWeather: GET failed: 401
08:29 0 8104

From here the NTP / Get location works, it finds me :) and sets the time right... 19:29 but then displays 8:29

Any ideas?

![image](https://user-images.githubusercontent.com/9491428/54385963-fd279780-46eb-11e9-9134-28f91f75bce0.png)

**Comment by dragondaud** [comment]
Error 401 is Unauthorized, maybe your weather creds got misconfigured?

**Comment by anthonyjclarke** [comment]
My Bad... I did a recompile with code that I had not entered my API tokens into :(
